### ISSUE TITLE
Emscripten cmake port

### ISSUE THREAD

**Issue by derofim** [assimp/assimp#1133]
First of all, big thanks to assimp team! I was very happy to see .X model in browser, Android and PC using almost same source code.

**Issue**:
In file https://github.com/assimp/assimp/blob/master/code/DefaultIOStream.cpp#L129 
`#elif` may be changed to something like (not sure, just added `__EMSCRIPTEN__`):

`#elif defined __gnu_linux__ || defined __APPLE__ || defined __MACH__ || defined __EMSCRIPTEN__`

That small fix will stop critical errors using build commands:
```
emcmake cmake -G "MinGW Makefiles" -DEMSCRIPTEN=1 -DCMAKE_TOOLCHAIN_FILE="%rootCMakeListsDir%/Emscripten.cmake" -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_ASSIMP_TOOLS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_C_FLAGS=-Wno-implicit-function-declaration -DCMAKE_CXX_FLAGS=-Wno-implicit-function-declaration -DCMAKE_BUILD_TYPE=Release  -DCMAKE_MODULE_PATH="%EMSCRIPTEN_PATH%/cmake/Modules" ..

emmake make
```

Emscripten toolchain im using (contains Emscripten.cmake and generated build/code/libassimp.so):
https://1drv.ms/u/s!AnTAt-3DzC4SvDCIDGUoer7VkG3C

Im linking libassimp.so using target_link_libraries (same for emcc below):
`emcc main.cpp libassimp.so -s USE_SDL=2 -s FULL_ES2=1 --preload-file res -o index.html -O3 -s ALLOW_MEMORY_GROWTH=1 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -s SDL2_IMAGE_FORMATS="['png']" -I"D:\assimp\emscripten\assimp-master\include"`

**Issue**:
Only .obj and .X loader works for me in browser (but in PC everything is fine), other file formats throws:
`ERROR::ASSIMP:: FBX-Tokenize (offset 0x1f) block offset is out of range`
or in .3ds loader (model http://www.turbosquid.com/FullPreview/Index.cfm/ID/240485 )
`ERROR::ASSIMP:: Chunk is too large`

Im using compile options:
`--emrun -std=c++14 -s USE_SDL=2 -s FULL_ES2=1 -O3 -s ALLOW_MEMORY_GROWTH=1 -s USE_SDL_IMAGE=2 -s USE_SDL_TTF=2 -s SDL2_IMAGE_FORMATS=\"['png']\" -s EXPORTED_FUNCTIONS=\"['_main', '_mainLoop']\" -s WARN_ON_UNDEFINED_SYMBOLS=1 -s SIMD=1 -s NO_EXIT_RUNTIME=1 -s SEPARATE_ASM=1 -s DISABLE_EXCEPTION_CATCHING=0 --preload-file ${PROJECT_ROOT_DIR}/samples/assets`

Added flags `-s ASSERTIONS=1 -std=c++14 -s SAFE_HEAP=1 -s DEMANGLE_SUPPORT=1 -s TOTAL_MEMORY=80088008`, revealed error:

`alignment fault
Uncaught abort("alignment fault") at Error
    at jsStackTrace (http://localhost:6931/samples.js:2885:13)
    at stackTrace (http://localhost:6931/samples.js:2902:22)
    at abort (http://localhost:6931/samples.js:650146:44)
    at alignfault (http://localhost:6931/samples.js:2027:3)
    at SAFE_HEAP_LOAD (http://localhost:6931/samples.js:636448:17)
    at __ZN6Assimp12StreamReaderILb0ELb0EE3GetIiEET_v [int Assimp::StreamReader<false, false>::Get<int>()] (http://localhost:6931/samples.js:615827:9)
    at __ZN6Assimp19Discreet3DSImporter9ReadChunkEPNS_4D3DS11Discreet3DS5ChunkE [Assimp::Discreet3DSImporter::ReadChunk(Assimp::D3DS::Discreet3DS::Chunk*)] (http://localhost:6931/samples.js:590041:7)
    at Array.__ZN6Assimp19Discreet3DSImporter14ParseMainChunkEv [Assimp::Discreet3DSImporter::ParseMainChunk()] (http://localhost:6931/samples.js:589800:3)
    at Object.dynCall_vi (http://localhost:6931/samples.js:645696:67)
    at invoke_vi (http://localhost:6931/samples.js:12750:25)
    at Array.__ZN6Assimp19Discreet3DSImporter14InternReadFileERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEP7aiScenePNS_8IOSystemE [Assimp::Discreet3DSImporter::InternReadFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, aiScene*, Assimp::IOSystem*)] (http://localhost:6931/samples.js:372119:7)
    at Object.dynCall_viiii (http://localhost:6931/samples.js:642651:68)
    at invoke_viiii (http://localhost:6931/samples.js:13155:28)
    at Array.__ZN6Assimp12BaseImporter8ReadFileEPKNS_8ImporterERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEPNS_8IOSystemE [Assimp::BaseImporter::ReadFile(Assimp::Importer const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Assimp::IOSystem*)] (http://localhost:6931/samples.js:500463:3)
    at Object.dynCall_iiiii (http://localhost:6931/samples.js:642360:75)
    at invoke_iiiii (http://localhost:6931/samples.js:13137:35)
    at Array.__ZN6Assimp8Importer8ReadFileEPKcj [Assimp::Importer::ReadFile(char const*, unsigned int)] (http://localhost:6931/samples.js:187502:19)
    at Object.dynCall_iiii (http://localhost:6931/samples.js:643281:74)
    at invoke_iiii (http://localhost:6931/samples.js:12858:34)
    at Array.__ZN6Assimp8Importer18ReadFileFromMemoryEPKvjjPKc [Assimp::Importer::ReadFileFromMemory(void const*, unsigned int, unsigned int, char const*)] (http://localhost:6931/samples.js:508566:4)
    at Object.dynCall_iiiiii (http://localhost:6931/samples.js:641734:76)
    at invoke_iiiiii (http://localhost:6931/samples.js:13020:36)
    at Array.__ZN5Model9loadModelENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE [Model::loadModel(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)] (http://localhost:6931/samples.js:486303:13)
    at Object.dynCall_vii (http://localhost:6931/samples.js:644508:68)
    at invoke_vii (http://localhost:6931/samples.js:12768:26)
    at Array.__ZN5ModelC2EPcP6Shader [Model::Model(char*, Shader*)] (http://localhost:6931/samples.js:587546:3)
    at Object.dynCall_viii (http://localhost:6931/samples.js:643609:67)
    at invoke_viii (http://localhost:6931/samples.js:13056:27)
    at __ZN16TriangleRenderer7InitGL3Ev [TriangleRenderer::InitGL3()] (http://localhost:6931/samples.js:127046:19)
    at Array.__ZN16TriangleRendererC2EP6Window [TriangleRenderer::TriangleRenderer(Window*)] (http://localhost:6931/samples.js:642096:2)
    at Object.dynCall_vii (http://localhost:6931/samples.js:644508:68)
    at invoke_vii (http://localhost:6931/samples.js:12768:26)
    at __Z4Initv [Init()] (http://localhost:6931/samples.js:634263:2)
    at _main (http://localhost:6931/samples.js:569624:2)
    at Object.asm._main (http://localhost:6931/samples.js:649619:19)
    at Object.callMain (http://localhost:6931/samples.js:650011:30)
    at doRun (http://localhost:6931/samples.js:650069:60)
    at http://localhost:6931/samples.js:650080:7`

May it help https://kripken.github.io/emscripten-site/docs/porting/Debugging.html#memory-alignment-issues ?

**Comment by turol** [comment]
See #461 and #1088.

**Comment by kimkulling** [comment]
OK, thanks for the feedback. I will try to fix this.

**Comment by turol** [comment]
https://github.com/assimp/assimp/blob/master/code/StreamReader.h#L293
Changing the conditional from
```
#ifdef __arm__
```
to
```
#if defined(__arm__) || defined(__EMSCRIPTEN__)
```
would be a good first step. Or even better, remove it entirely and leave only the first version. Any optimizing compiler should generate the same code from both and the second version is UB.

**Comment by makc** [comment]
just to repeat [stuff I just wrote](https://github.com/makc/assimp2json/issues/2) here:
- you need to address #340 first unless you want to write js interfaces for everything in assimp;
- only wasm build works, default emscripten build fails in half of cases.

**Comment by makc** [comment]
oh, and btw - someone already did cmake thing [here](https://github.com/Shervanator/Engine/blob/master/scripts/cmake-emscripten.sh) as a part of their own project - so you have that starting point.

**Comment by kimkulling** [comment]
Thanks a lot for the hint!

**Comment by clinthidinger** [comment]
I've done some work on an emscripten port: https://github.com/clinthidinger/assimp.js.  I used embind to make the js interfaces.  It still needs some work and testing, but I do have two functioning samples.  One converts to three.js and back.  Apologies if this is not the correct place to share this.

**Comment by kimkulling** [comment]
Seems to be related to my openddl-parser experiment.

**Comment by EvilPudding** [comment]
What is the current state of emscripten assimp? There's sprinklings of how to do it here and there, but I can't see the full picture.

What are the steps minimum steps required in order to port a project that uses assimp as a dynamic library into the browser?

Is there an official makefile or cmake list?

**Comment by kimkulling** [comment]
Hi,

in short: experiments are ongoing, but no product. 

Kim

**Comment by EvilPudding** [comment]
Thanks for the answer. What parts aren't working? Is it just exporting or importing as well? Are there formats that are known to work and formats that are known to break?

**Comment by hotchocolate314** [comment]
Hi, has anyone been able to get an emscripten port working? I've tried building it as a static lib on Linux and using emcmake/emmake and just including it in emcc, but I end up with a number of undefined references. What other reasons would there be why this doesn't seem to be working? (And is there a way to get around them)?
For reference the errors I'm getting are undefined symbols:
![image](https://user-images.githubusercontent.com/54476710/88875713-af94c780-d219-11ea-9fc4-f61ac0ddaf9d.png)
^ And many more

**Comment by kiyoMatsui** [comment]
Hi Koushik, I get:
 wasm-ld: error: --shared-memory is disallowed by DefaultIOSystem.cpp.o because it was not compiled with 'atomics' or 'bulk-memory' features.
I'll have to look another day why, but any ideas are welcome. Thanks.

**Comment by makc** [comment]
looks like [this guy](https://github.com/kovacsv/assimpjs) has you covered

**Comment by d3fault** [comment]
I successfully compiled assimp for WebAssembly using Emscripten SDK and used it a C++ project ([Demo](http://d3fault.github.io/wasm-3d-demos/bgfx-assimp-3d-pbr-ibl-shiny-drill/index.html) - [Source](https://github.com/d3fault/bgfx-assimp-3d-pbr-ibl-shiny-drill)) without making any changes at all to assimp, so I guess this "bug" is solved? The only weird thing I did was `emcmake cmake .. -DASSIMP_BUILD_ZLIB=ON` but then I used the zlib port that comes with Emscripten SDK `-s USE_ZLIB=1` out of laziness and hey it worked so I'm not gonna fix it :-P.

@makc I think assimpjs is for people who want to code in JS

**Comment by makc** [comment]
@d3fault yes I think they made it possible years ago.

**Comment by tellypresence** [comment]
Looks like this got solved at some point, please re-open if it's still a problem

**Comment by d3fault** [comment]
>@makc 
> what other reason would be to compile assimp to wasm?

To be able to use assimp from C++ that's also been compiled to wasm ([example](https://github.com/d3fault/bgfx-assimp-3d-pbr-ibl-shiny-drill))
