### ISSUE TITLE
IFCBoolean.cpp: Division by zero

### ISSUE THREAD

**Issue by turol** [assimp/assimp#1481]
With UBsan enabled (#1480) 

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from utIFCImportExport
[ RUN      ] utIFCImportExport.importIFCFromFileTest
code/IFCBoolean.cpp:275:36: runtime error: division by zero
```

The offending line:
```
        IfcFloat b_sqlen_inv = 1.0 / b.SquareLength();
```

With gdb (well, rr actually but almost the same):
```
(rr) insp b
$1 = {x = 0, y = 0, z = 0}
(rr) insp boundary
$2 = std::vector of length 5, capacity 5 = {{x = 5, y = -0.45000000000000001, z = 0}
, {x = 5, y = 0.14999999999999999, z = 0}
, {x = 10.01, y = 0.14999999999999999, z = 0}
, {x = 10.01, y = -0.45000000000000001, z = 0}
, {x = 5,  y = -0.45000000000000001, z = 0}}
(rr) insp b0
$3 = (const Assimp::IFC::IfcVector3 &) @0xa1a2bb0: {x = 5, y = -0.45000000000000001, z = 0}
(rr) insp b1
$4 = (const Assimp::IFC::IfcVector3 &) @0xa1a2b50: {x = 5, y = -0.45000000000000001, z = 0}
(rr) insp i
$5 = 4
(rr) insp bcount
$6 = 5

#3  0x00000000024b55ee in Assimp::IFC::IntersectsBoundaryProfile (e0=..., e1=..., boundary=std::vector of length 5, capacity 5 = {...}, isStartAssumedInside=true, intersect_results=std::vector of length 1, capacity 1 = {...}, 
    halfOpen=true) at code/IFCBoolean.cpp:275
#4  0x00000000024b866c in Assimp::IFC::PointInPoly (p=..., boundary=std::vector of length 5, capacity 5 = {...}) at code/IFCBoolean.cpp:373
#5  0x00000000024bcb82 in Assimp::IFC::ProcessPolygonalBoundedBooleanHalfSpaceDifference (hs=0xa179f40, result=..., first_operand=..., conv=...) at code/IFCBoolean.cpp:513
#6  0x00000000024c753f in Assimp::IFC::ProcessBoolean (boolean=..., result=..., conv=...) at code/IFCBoolean.cpp:812
#7  0x00000000024c6c2c in Assimp::IFC::ProcessBoolean (boolean=..., result=..., conv=...) at code/IFCBoolean.cpp:798
#8  0x0000000002435a3b in Assimp::IFC::ProcessGeometricItem (geo=..., matid=0, mesh_indices=std::vector of length 0, capacity 0, conv=...) at code/IFCGeometry.cpp:771
#9  0x000000000243885f in Assimp::IFC::ProcessRepresentationItem (item=..., matid=4294967295, mesh_indices=std::vector of length 0, capacity 0, conv=...) at code/IFCGeometry.cpp:871
#10 0x0000000001d1e488 in (anonymous namespace)::ProcessProductRepresentation (el=..., nd=0xa178c50, subnodes=std::vector of length 1, capacity 1 = {...}, conv=...) at code/IFCLoader.cpp:576
#11 0x0000000001d19e7e in (anonymous namespace)::ProcessSpatialStructure (parent=0xa176ad0, el=..., conv=..., collect_openings=0x0) at code/IFCLoader.cpp:844
#12 0x0000000001d1566e in (anonymous namespace)::ProcessSpatialStructure (parent=0x9a1ad90, el=..., conv=..., collect_openings=0x0) at code/IFCLoader.cpp:760
#13 0x0000000001d19512 in (anonymous namespace)::ProcessSpatialStructure (parent=0x9a1a1d0, el=..., conv=..., collect_openings=0x0) at code/IFCLoader.cpp:827
#14 0x0000000001d19512 in (anonymous namespace)::ProcessSpatialStructure (parent=0x0, el=..., conv=..., collect_openings=0x0) at code/IFCLoader.cpp:827
#15 0x0000000001d0c425 in (anonymous namespace)::ProcessSpatialStructures (conv=...) at code/IFCLoader.cpp:910
#16 0x0000000001d05bd2 in Assimp::IFCImporter::InternReadFile (this=0x8d79030, pFile="test/models/IFC/AC14-FZK-Haus.ifc", pScene=0x8d7bcf0, pIOHandler=0x7ffddac1ca58) at code/IFCLoader.cpp:279
#17 0x0000000000b1c67c in Assimp::BaseImporter::ReadFile (this=0x8d79030, pImp=0x7ffddac1d230, pFile="test/models/IFC/AC14-FZK-Haus.ifc", pIOHandler=0x8d763d0) at code/BaseImporter.cpp:97
#18 0x0000000000b7431a in Assimp::Importer::ReadFile (this=0x7ffddac1d230, _pFile=0x359d826 "test/models/IFC/AC14-FZK-Haus.ifc", pFlags=0) at code/Importer.cpp:677
#19 0x000000000095b081 in utIFCImportExport::importerTest (this=0x8d76380) at test/unit/utIFCImportExport.cpp:53
#20 0x000000000095a6e2 in utIFCImportExport_importIFCFromFileTest_Test::TestBody (this=0x8d76380) at test/unit/utIFCImportExport.cpp:61
#21 0x000000000086270b in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (object=0x8d76380, method=&virtual testing::Test::TestBody(), location=0x35699aa "the test body")
    at test/../contrib/gtest/src/gtest.cc:2402
#22 0x00000000007ec164 in testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x8d76380, method=&virtual testing::Test::TestBody(), location=0x35699aa "the test body")
    at test/../contrib/gtest/src/gtest.cc:2438
#23 0x000000000076ac03 in testing::Test::Run (this=0x8d76380) at test/../contrib/gtest/src/gtest.cc:2474
#24 0x000000000076ea3e in testing::TestInfo::Run (this=0x8d66940) at test/../contrib/gtest/src/gtest.cc:2656
#25 0x0000000000771530 in testing::TestCase::Run (this=0x8d66b50) at test/../contrib/gtest/src/gtest.cc:2774
#26 0x000000000079a628 in testing::internal::UnitTestImpl::RunAllTests (this=0x8d600c0) at test/../contrib/gtest/src/gtest.cc:4649
#27 0x000000000087476d in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x8d600c0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x798780 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x356a0c4 "auxiliary test code (environments or event listeners)")
    at test/../contrib/gtest/src/gtest.cc:2402
#28 0x00000000007f8cf4 in testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x8d600c0, 
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x798780 <testing::internal::UnitTestImpl::RunAllTests()>, location=0x356a0c4 "auxiliary test code (environments or event listeners)")
    at test/../contrib/gtest/src/gtest.cc:2438
#29 0x000000000079867c in testing::UnitTest::Run (this=0x71a2580 <testing::UnitTest::GetInstance()::instance>) at test/../contrib/gtest/src/gtest.cc:4257
#30 0x000000000088a7f8 in RUN_ALL_TESTS () at test/../contrib/gtest/include/gtest/gtest.h:2233
#31 0x000000000088a489 in main (argc=1, argv=0x7ffddac1e048) at test/unit/Main.cpp:26


```

**Comment by turol** [comment]
Fixed by #1480
