### ISSUE TITLE
PyAssimp fails to load some of the test-files (face-index lists of varying length)

### ISSUE THREAD

**Issue by umlaeute** [assimp/assimp#2817]
after resolving #2788, I still get (non-fatal, catchable) errors when trying to load the following few test-files with PyAssimp:

- `test/models/OBJ/testmixed.obj`
- `test/models/OFF/invalid.off`
- `test/models/DXF/lineTest.dxf`
- `test/models/DXF/issue_2229.dxf`

all models fail with the error:
> ValueError: setting an array element with a sequence.

e.g.:
~~~sh
$ python3 -c 'import pyassimp;pyassimp.load("test/models/OBJ/testmixed.obj")'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 183, in _init
    init = assimp_struct_inits[type(obj[0])]
KeyError: <class 'pyassimp.structs.LP_Mesh'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 320, in load
    scene = _init(model.contents)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 206, in _init
    raise e
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 187, in _init
    call_init(e, target)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 80, in call_init
    _init(obj.contents, obj, caller)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 218, in _init
    _finalize_mesh(self, target)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 435, in _finalize_mesh
    faces = numpy.array([f.indices for f in target.faces], dtype=numpy.int32)
ValueError: setting an array element with a sequence.
~~~

**Comment by umlaeute** [comment]
the problem only exists when using `numpy`.

the problem is obviously, that [core.py:435](https://github.com/assimp/assimp/blob/d8575b2b55ba1195de58a2bc97330879b3deb2e0/port/PyAssimp/pyassimp/core.py#L435) attempts to create a numpy-array from a list of a list of indices - but these sublists can have varying lengths. Since numpy arrays must have a fixed dimension, it cannot really handle variable-length face-indices.

Afaics there's two options: 

- [ ] python `list`s of `list`s

      faces = [f.indices for f in target.faces]

- [ ] a `numpy.array` of `numpy.array`s.

      faces = numpy.array([numpy.array(f.indices, dtype=numpy.int32) for f in target.faces])

the former will break at least [scripts/sample.py](https://github.com/assimp/assimp/blob/master/port/PyAssimp/scripts/sample.py#L46), but that's easily fixable.

the latter is probably more what you want...

PS: i'd like to include a fix in the Debian package ASAP, so even if you don't find the time to fix this problem right now I'd welcome some feedback on what you are planning to do (and what you will definitely not do).

**Comment by kimkulling** [comment]
Ok, thanks a lot for the investigation!
