### ISSUE TITLE
PyAssImp 3d_viewer_py3.py not running

### ISSUE THREAD

**Issue by CatsNipYummy** [assimp/assimp#2842]
I've been trying to run the 3d_viewer_py3.py from the python port. I get the following error.

Python version - 3.6.9
PyGame version - 1.9.6
NumPy version - 1.17.2
Ubuntu 18.04

`python3 3d_viewer_py3.py /home/user/assimp/test/models/OBJ/box.obj`

Do I need another version of numpy?

Error:

```
python3 3d_viewer_py3.py /home/user/assimp/test/models/OBJ/box.obj
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO:pyassimp:Adding Anaconda lib path:/home/user/anaconda3/envs/hugo/lib/
INFO:pyassimp:Loading model:/home/user/assimp/test/models/OBJ/box.obj...
INFO:pyassimp:Done.
INFO:pyassimp:  meshes: 1
INFO:pyassimp:  total faces: 12
INFO:pyassimp:  materials: 1
Traceback (most recent call last):
  File "3d_viewer_py3.py", line 1316, in <module>
    main(model=sys.argv[1], width=1024, height=768)
  File "3d_viewer_py3.py", line 1278, in main
    app = PyAssimp3DViewer(model, w=width, h=height)
  File "3d_viewer_py3.py", line 496, in __init__
    self.load_model(model)
  File "3d_viewer_py3.py", line 694, in load_model
    self.bb_min, self.bb_max = get_bounding_box(self.scene)
  File "/home/user/anaconda3/envs/hugo/lib/python3.6/site-packages/pyassimp/helper.py", line 114, in get_bounding_box
    return get_bounding_box_for_node(scene.rootnode, bb_min, bb_max, inv(scene.rootnode.transformation))
  File "<__array_function__ internals>", line 6, in inv
  File "/home/user/anaconda3/envs/hugo/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 551, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/user/anaconda3/envs/hugo/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 97, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

I've tried other models as well. But similar issue. 

`python sample.py /home/user/assimp/test/models/OBJ/box.obj` works fine. But I want to get the viewer to work.

**Comment by kimkulling** [comment]
I guess the problem is caused by an invalid transformation matrix in the model. Have you tried a more complex one? Maybe the import does not try to generate a root-transformation in this case when using the python bindings.

**Comment by yves-surrel** [comment]
Same problem here, with different models.

**Comment by AnnaMei11** [comment]
Did anyone find a solution to this? Is it a problem with pyassimp or just this example script?

**Comment by tellypresence** [comment]
@unnikrishnan-anil Is this still a problem?

**Comment by tellypresence** [comment]
Closing old issue, please reopen if it's still a problem
