### ISSUE TITLE
IFC import crash

### ISSUE THREAD

**Issue by arturredzko** [assimp/assimp#2993]
Hi
I get crash (Exception thrown: read access violation.) when processing IfcRepresentationItems during reading of this project 
[Brucke.zip](https://github.com/assimp/assimp/files/4177092/Brucke.zip)
Can you check what's wrong?

**Comment by arturredzko** [comment]
Here is another example of a crash during the triangulation process 
[S10.zip](https://github.com/assimp/assimp/files/4184933/S10.zip)
I've tried many IFC models from the assimp repository and a lot of them fail to import or crash during triangulation.

**Comment by turol** [comment]
S10.ifc loads correctly for me. Brucke.ifc fails with:
```
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000020 (pc 0x000000d5e5b8 bp 0x7ffdbb7ec6b0 sp 0x7ffdbb7ebe70 T0)
The signal is caused by a READ memory access.
Hint: address points to the zero page.
    #0 0xd5e5b7 in Assimp::STEP::LazyObject::operator*() const assimp/code/Step/STEPFile.h:617:18
    #1 0xd6b455 in Assimp::IFC::Schema_2x3::IfcRepresentationItem const& Assimp::STEP::LazyObject::To<Assimp::IFC::Schema_2x3::IfcRepresentationItem>() const assimp/code/Step/STEPFile.h:626:44
    #2 0xd58692 in (anonymous namespace)::ProcessMappedItem(Assimp::IFC::Schema_2x3::IfcMappedItem const&, aiNode*, std::vector<aiNode*, std::allocator<aiNode*> >&, unsigned int, Assimp::IFC::ConversionData&) assimp/code/Importer/IFC/IFCLoader.cpp:467:55
    #3 0xd571fe in (anonymous namespace)::ProcessProductRepresentation(Assimp::IFC::Schema_2x3::IfcProduct const&, aiNode*, std::vector<aiNode*, std::allocator<aiNode*> >&, Assimp::IFC::ConversionData&) assimp/code/Importer/IFC/IFCLoader.cpp:583:23
    #4 0xd55bb0 in (anonymous namespace)::ProcessSpatialStructure(aiNode*, Assimp::IFC::Schema_2x3::IfcProduct const&, Assimp::IFC::ConversionData&, std::vector<Assimp::IFC::TempOpening, std::allocator<Assimp::IFC::TempOpening> >*) assimp/code/Importer/IFC/IFCLoader.cpp:852:11
    #5 0xd550d0 in (anonymous namespace)::ProcessSpatialStructure(aiNode*, Assimp::IFC::Schema_2x3::IfcProduct const&, Assimp::IFC::ConversionData&, std::vector<Assimp::IFC::TempOpening, std::allocator<Assimp::IFC::TempOpening> >*) assimp/code/Importer/IFC/IFCLoader.cpp:768:43
    #6 0xd55a60 in (anonymous namespace)::ProcessSpatialStructure(aiNode*, Assimp::IFC::Schema_2x3::IfcProduct const&, Assimp::IFC::ConversionData&, std::vector<Assimp::IFC::TempOpening, std::allocator<Assimp::IFC::TempOpening> >*) assimp/code/Importer/IFC/IFCLoader.cpp:835:47
    #7 0xd55a60 in (anonymous namespace)::ProcessSpatialStructure(aiNode*, Assimp::IFC::Schema_2x3::IfcProduct const&, Assimp::IFC::ConversionData&, std::vector<Assimp::IFC::TempOpening, std::allocator<Assimp::IFC::TempOpening> >*) assimp/code/Importer/IFC/IFCLoader.cpp:835:47
    #8 0xd53176 in (anonymous namespace)::ProcessSpatialStructures(Assimp::IFC::ConversionData&) assimp/code/Importer/IFC/IFCLoader.cpp:917:23
    #9 0xd51489 in Assimp::IFCImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) assimp/code/Importer/IFC/IFCLoader.cpp:294:5
    #10 0x8e4c2e in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) assimp/code/Common/BaseImporter.cpp:130:9
    #11 0x647f2f in Assimp::Importer::ReadFile(char const*, unsigned int) assimp/code/Common/Importer.cpp:656:30
    #12 0x638e67 in ImportModel(ImportData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) assimp/tools/assimp_cmd/Main.cpp:289:41
    #13 0x63ea4e in Assimp_Info(char const* const*, unsigned int) assimp/tools/assimp_cmd/Info.cpp:332:25
    #14 0x638a58 in main assimp/tools/assimp_cmd/Main.cpp:207:10
    #15 0x7fa557a36bba in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26bba)
    #16 0x574aa9 in _start (assimp/asan/tools/assimp_cmd/assimp+0x574aa9)
```
It's referencing a NULL pointer.

**Comment by arturredzko** [comment]
yes, that is the crash. S10 loads fine when using flags 0, but if I add a triangulation flag (preset Fast or Quality) then I get a crash inside the triangulation code.

**Comment by arturredzko** [comment]
BTW. Are materials read correctly from IFC, I have no colors or textures but on another viewer, they are painted
![image](https://user-images.githubusercontent.com/4385342/74410239-f2640e00-4e38-11ea-9ec0-be080836c1e7.png)

**Comment by arturredzko** [comment]
Any chance to fix this bug?

**Comment by arturred** [comment]
I don't want to create a new issue, just add another sample that fails to open with the error **'Bad dynamic_cast!'**.
[811.zip](https://github.com/assimp/assimp/files/6629900/811.zip)

**Comment by tellypresence** [comment]
Results on recent assimp git commit:

<table>
<tr><th>Model</th><th>Load result</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/files/6629900/811.zip"><tt>811.ifc</tt></a></td><td>Load attempt fails with error <tt>IFC: Unrecognized file schema: IFC4</tt></td></tr>
<tr><td><a href="https://github.com/assimp/assimp/files/4177092/Brucke.zip"><tt>Brucke.ifc</tt></a></td><td>Load attempt fails with error <tt>IFC: Unrecognized file schema: IFC4</tt></td></tr>
<tr><td><a href="https://github.com/assimp/assimp/files/4184933/S10.zip"><tt>S10.IFC</tt></a></td><td>Load attempt crashes on my implementation</td></tr>
</table>
