### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by a-anjos** [assimp/assimp#3066]
Hi when doing:
``sudo pip3 install AssimpCy``
I get:

> running egg_info
    creating pip-egg-info/AssimpCy.egg-info
    writing pip-egg-info/AssimpCy.egg-info/PKG-INFO
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3dm_ai2z/AssimpCy/setup.py", line 88, in <module>
        requires=['numpy']
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 289, in run
        writer(self, ep.name, os.path.join(self.egg_info, ep.name))
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 621, in write_pkg_info
        metadata.write_pkg_info(cmd.egg_info)
      File "/usr/lib/python3.7/distutils/dist.py", line 1117, in write_pkg_info
        self.write_pkg_file(pkg_info)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 166, in write_pkg_file
        long_desc = rfc822_escape(self.get_long_description())
      File "/usr/lib/python3.7/distutils/util.py", line 464, in rfc822_escape
        lines = header.split('\n')
    TypeError: a bytes-like object is required, not 'str'

**Comment by a-anjos** [comment]
Sorry, this is another package :)

**Comment by kimkulling** [comment]
Not to worry!
