### ISSUE TITLE
Sanitizer/adress-sanitizer test detects 4 byte memory leak in master

### ISSUE THREAD

**Issue by RichardTea** [assimp/assimp#3200]
This causes a github actions error email to go out for every PR, which is quite irritating.

Leak is blamed on:
```aiMetadata::Set<float>(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float const&) /home/runner/work/assimp/assimp/build/../include/assimp/metadata.h:317:32```

Full stack trace:

```
2020-05-01T14:03:26.3628287Z =================================================================
2020-05-01T14:03:26.3628480Z ==4544==ERROR: LeakSanitizer: detected memory leaks
2020-05-01T14:03:26.3628636Z 
2020-05-01T14:03:26.3628931Z Direct leak of 4 byte(s) in 1 object(s) allocated from:
2020-05-01T14:03:26.3631245Z     #0 0x57370d in operator new(unsigned long) (/home/runner/work/assimp/assimp/build/bin/unit+0x57370d)
2020-05-01T14:03:26.3633145Z     #1 0x7f6225d776c1 in bool aiMetadata::Set<float>(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float const&) /home/runner/work/assimp/assimp/build/../include/assimp/metadata.h:317:32
2020-05-01T14:03:26.3635249Z     #2 0x7f62264b9544 in Assimp::FBX::FBXConverter::ConvertGlobalSettings() /home/runner/work/assimp/assimp/build/../code/FBX/FBXConverter.cpp:3405:27
2020-05-01T14:03:26.3640144Z     #3 0x7f62264b6064 in Assimp::FBX::FBXConverter::FBXConverter(aiScene*, Assimp::FBX::Document const&, bool) /home/runner/work/assimp/assimp/build/../code/FBX/FBXConverter.cpp:131:5
2020-05-01T14:03:26.3640740Z     #4 0x7f62264fda88 in Assimp::FBX::ConvertToAssimpScene(aiScene*, Assimp::FBX::Document const&, bool) /home/runner/work/assimp/assimp/build/../code/FBX/FBXConverter.cpp:3503:18
2020-05-01T14:03:26.3643101Z     #5 0x7f62264938a4 in Assimp::FBXImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) /home/runner/work/assimp/assimp/build/../code/FBX/FBXImporter.cpp:181:3
2020-05-01T14:03:26.3643292Z     #6 0x7f6225677d27 in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) /home/runner/work/assimp/assimp/build/../code/Common/BaseImporter.cpp:130:9
2020-05-01T14:03:26.3643455Z     #7 0x7f62256bdfec in Assimp::Importer::ReadFile(char const*, unsigned int) /home/runner/work/assimp/assimp/build/../code/Common/Importer.cpp:656:30
2020-05-01T14:03:26.3643598Z     #8 0x73b8c4 in utFBXImporterExporter_importUnitScaleFactor_Test::TestBody() /home/runner/work/assimp/assimp/build/../test/unit/utFBXImporterExporter.cpp:208:37
2020-05-01T14:03:26.3643758Z     #9 0x607a7b in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2402:10
2020-05-01T14:03:26.3643943Z     #10 0x5cdcdf in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2438:14
2020-05-01T14:03:26.3652146Z     #11 0x592552 in testing::Test::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2474:5
2020-05-01T14:03:26.3652296Z     #12 0x5945f3 in testing::TestInfo::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2656:11
2020-05-01T14:03:26.3652426Z     #13 0x59577b in testing::TestCase::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2774:28
2020-05-01T14:03:26.3652720Z     #14 0x5a6c96 in testing::internal::UnitTestImpl::RunAllTests() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:4649:43
2020-05-01T14:03:26.3652892Z     #15 0x6100a6 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2402:10
2020-05-01T14:03:26.3653067Z     #16 0x5d391f in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2438:14
2020-05-01T14:03:26.3653221Z     #17 0x5a61fa in testing::UnitTest::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:4257:10
2020-05-01T14:03:26.3653349Z     #18 0x61a7c0 in RUN_ALL_TESTS() /home/runner/work/assimp/assimp/build/../contrib/gtest/include/gtest/gtest.h:2233:46
2020-05-01T14:03:26.3653470Z     #19 0x61a6a2 in main /home/runner/work/assimp/assimp/build/../test/unit/Main.cpp:26:18
2020-05-01T14:03:26.3654423Z     #20 0x7f6223b64b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
2020-05-01T14:03:26.3654506Z 
2020-05-01T14:03:26.3655275Z SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
2020-05-01T14:03:26.3931749Z ##[error]Process completed with exit code 1.
```

**Comment by turol** [comment]
Duplicate of #3190. I already debugged it, someone (else) just needs to fix it.
