### ISSUE TITLE
AccessViolation crash on blend model load

### ISSUE THREAD

**Issue by andrejkudinov** [assimp/assimp#3230]
Hello,
When I try to load the publicly available BLEND model from the following [https://free3d.com/3d-model/bugatti-chiron-2017-model-31847.html](source), a System.AccessViolationException occurs.

Used configuration:
Assimp v5.0.0.0 with assimp-net wrapper.

Please, let me know if you need more information.

Thanks.

**Comment by turol** [comment]
Confirmed with latest master. With Asan on Linux:
```
ERROR: AddressSanitizer: SEGV on unknown address 0x000000000598 (pc 0x000001298665 bp 0x7ffdcbe064d0 sp 0x7ffdcbe064c0 T0)
The signal is caused by a READ memory access.
Hint: address points to the zero page.
    #0 0x1298664 in std::__shared_ptr<Assimp::Blender::MTex, (__gnu_cxx::_Lock_policy)2>::operator bool() const /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/shared_ptr_base.h
    #1 0x128be40 in Assimp::BlenderImporter::ConvertMesh(Assimp::Blender::Scene const&, Assimp::Blender::Object const*, Assimp::Blender::Mesh const*, Assimp::Blender::ConversionData&, Assimp::Blender::TempArray<std::vector, aiMesh>&) code/Blender/BlenderLoader.cpp:1040:17
    #2 0x127cd1d in Assimp::BlenderImporter::ConvertNode(Assimp::Blender::Scene const&, Assimp::Blender::Object const*, Assimp::Blender::ConversionData&, aiMatrix4x4t<float> const&) code/Blender/BlenderLoader.cpp:1315:13
    #3 0x127afca in Assimp::BlenderImporter::ConvertBlendFile(aiScene*, Assimp::Blender::Scene const&, Assimp::Blender::FileDatabase const&) code/Blender/BlenderLoader.cpp:375:30
    #4 0x127866a in Assimp::BlenderImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) code/Blender/BlenderLoader.cpp:263:5
    #5 0xb30437 in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) code/Common/BaseImporter.cpp:130:9
    #6 0x67eedc in Assimp::Importer::ReadFile(char const*, unsigned int) code/Common/Importer.cpp:656:30
    #7 0x660725 in Assimp::Importer::ReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) include/assimp/Importer.hpp:648:12
    #8 0x65e155 in ImportModel(ImportData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) tools/assimp_cmd/Main.cpp:289:41
    #9 0x66836b in Assimp_Info(char const* const*, unsigned int) tools/assimp_cmd/Info.cpp:332:25
    #10 0x65da4d in main tools/assimp_cmd/Main.cpp:207:10
    #11 0x7fda63474e0a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26e0a)
    #12 0x584079 in _start (asan/bin/assimp+0x584079)

```

**Comment by kimkulling** [comment]
Shall be fixed rigt now: https://github.com/assimp/assimp/pull/4193.

Just reopen if this is still an issue.
