### ISSUE TITLE
v4.1.0 returns an empty scene when loading a Blender-generated glTF file

### ISSUE THREAD

**Issue by kunimatsu-tri** [assimp/assimp#3507]
Hi, 

**Describe the bug**

- When `pyassimp` loads Blender-generated glTF file, the loaded scene becomes empty.
- When `pyassimp` loads a glTF file which has the word `Blender` in its `generator` field, `pyassimp` raises an error.

This happened when I tried to load a glTF file generated by Blender's export functionality using `pyassimp`.

The Blender-generated glTF file should contain meta-information which looks something like this:
```
    "asset" : {
        "generator" : "Khronos glTF Blender I/O v1.3.48",
        "version" : "2.0"
    },
```

then, loading this file using `pyassimp.load` function returns an empty scene even if the scene is not empty. 

Surprisingly, if you replace the string for the `generator` field as follows:

```
  "asset": {
    "generator": "arbitrary_string",
    "version": "2.0"
  },
```
`pyassimp.load` now returns a non-empty valid scene.

Moreover, if you replace the string for the `generator` field with the word `Blender`:
```
  "asset": {
    "generator": "Blender",
    "version": "2.0"
  },
```
`pyassimp` raises an error.

Note that the other contents in the glTF stay the same. These things happen just by swapping the string for the `generator` field.

**To Reproduce**
1. Install `pyassimp` via `apt` command.
```
sudo apt install python3-pyassimp
```

2. Clone `assimp` (just to get `sample.py` script) and `cd` to the following directory:
```
git clone git@github.com:assimp/assimp.git
cd assimp/port/PyAssimp/scripts
```

3. Download these [gltf](https://github.com/kunimatsu-tri/assimp/blob/repro/port/PyAssimp/scripts/default_box.gltf) and [bin](https://github.com/kunimatsu-tri/assimp/blob/repro/port/PyAssimp/scripts/default_box.bin) files and save them under the `scripts` directory. Note that these files are created by Blender's export functionality  (File -> Export -> glTF 2.0) and the scene is the default box that you'll always have when you launch the Blender GUI.

4. Run the following commands:
```
python3 sample.py default_box.gltf
```
and see the output on your terminal. It should look like this:

```
MODEL:default_box.gltf
SCENE:
  meshes:0
  materials:1
  textures:0
NODES:
  - default_box.gltf
MESHES:
MATERIALS:
  MATERIAL (id:1)
    name: DefaultMaterial
    shadingm: 2
    ambient: [0.0, 0.0, 0.0]
    diffuse: [0.6000000238418579, 0.6000000238418579, 0.6000000238418579]
    specular: [0.0, 0.0, 0.0]
    emissive: [0.0, 0.0, 0.0]
    shininess: 0.0
    opacity: 1.0
    transparent: [1.0, 1.0, 1.0]
    refracti: 1.0
TEXTURES:
```

See `meshes:0`. So, the loader is returning an empty scene in this case.

5. Open the `default_box.gltf` using your favorite text editor and swap the text for the `generator` field with `arbitry_string` (could be anything) and run the same command as No. 4. Now you should see the valid contents which should look like this:
```
MODEL:default_box.gltf
SCENE:
  meshes:1
  materials:1
  textures:0
NODES:
  - ROOT
  	- Cube
  	- Light
  	- Camera
MESHES:
  MESH1
    material id:1
    vertices:36
    first 3 verts:
[[ 1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  1. -1.]]
    first 3 normals:
[[ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
    colors:0
    texture-coords 0:36first3:[[ 0.625  0.75   0.   ]
 [ 0.625  0.5    0.   ]
 [ 0.875  0.5    0.   ]]
    uv-component-count:8
    faces:12 -> first:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
    bones:0 -> first:[]
MATERIALS:
  MATERIAL (id:1)
    name: Material
    diffuse: [0.800000011920929, 0.800000011920929, 0.800000011920929, 1.0]
    gltf: 0.5
    shininess: 600.0
    emissive: [0.0, 0.0, 0.0, 1.0]
    twosided: 1
TEXTURES:
```
6. Swap the text for the `generator` field with `Blender` this time, and run the same command as No. 4. In this case, `pyassimp` raises the following error:
```
Traceback (most recent call last):
  File "sample.py", line 89, in <module>
    main(sys.argv[1])
  File "sample.py", line 23, in main
    scene = pyassimp.load(filename, processing=pyassimp.postprocess.aiProcess_Triangulate)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 318, in load
    raise AssimpError('Could not import file!')
pyassimp.errors.AssimpError: Could not import file!
```

**Expected behavior**
The result from No. 5 in the **To Reproduce** section is the expected behavior. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS:Ubuntu 18.04

**Smartphone (please complete the following information):**
N/A

**Additional context**
Here is the `pyassimp` version that I use:
```
dpkg -s python3-pyassimp | grep Version
Version: 4.1.0~dfsg-3
```

Thanks!

**Comment by contriteobserver** [comment]
The issue is not limited to `pyassimp`, reconfirmed that if one `git checkout tags/v4.1.0 -b v4.1.0-branch` and rebuilds,
the command `~/assimp/Release/tools/assimp_cmd/assimp info ../port/PyAssimp/scripts/default_box.gltf`will output:
```
Launching asset import ...           OK
Validating postprocessing flags ...  OK
ERROR: Failed to load file: Validation failed: aiScene::mNumMeshes is 0. At least one mesh must be there
assimp info: Unable to load input file ../port/PyAssimp/scripts/default_box.gltf
```

However, with `git checkout master` the command `~/assimp/Release/bin/assimp info ../port/PyAssimp/scripts/default_box.gltf` will output:
```
Launching asset import ...           OK
Validating postprocessing flags ...  OK
Importing file ...                   OK 
   import took approx. 0.00396 seconds

Memory consumption: 9037 B
Nodes:              4
Maximum depth       2
Meshes:             1
Animations:         0
Textures (embed.):  0
Materials:          1
Cameras:            0
Lights:             0
Vertices:           24
Faces:              12
Bones:              0
Animation Channels: 0
Primitive Types:    triangles
Average faces/mesh  12
Average verts/mesh  24
Minimum point      (-1.000000 -1.000000 -1.000000)
Maximum point      (1.000000 1.000000 1.000000)
Center point       (0.000000 0.000000 0.000000)

Meshes:  (name) [vertices / bones / faces | primitive_types]
    0 (Cube): [24 / 0 / 12 | triangle]

Named Materials:
    'Material'

Node hierarchy:
ROOT
├╴Cube (mesh 0)
├╴Light
└╴Camera
```

**Comment by valina354** [comment]
im having the same issue, whats going on?

**Comment by tellypresence** [comment]
Please add label "pysassimp" to this issue

**Comment by tellypresence** [comment]
@kunimatsu-tri Is this still a problem?

**Comment by tellypresence** [comment]
Closing due to no response to followup
