### ISSUE TITLE
pyassimp.errors.AssimpError: assimp library not found

### ISSUE THREAD

**Issue by Mr-Xia-6** [assimp/assimp#3508]
Ubuntu16    conda--python3.6.9
```
(omg) yusheng@yusheng:~/OMG-Planner/ycb_render$ pip install pyassimp==4.1.3
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pyassimp==4.1.3 in /home/yusheng/anaconda3/envs/omg/lib/python3.6/site-packages (4.1.3)
(omg) yusheng@yusheng:~/OMG-Planner/ycb_render$ python ycb_renderer.py ycb
Traceback (most recent call last):
  File "ycb_renderer.py", line 14, in <module>
    from pyassimp import *
  File "/home/yusheng/anaconda3/envs/omg/lib/python3.6/site-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/home/yusheng/anaconda3/envs/omg/lib/python3.6/site-packages/pyassimp/core.py", line 34, in <module>
    class AssimpLib(object):
  File "/home/yusheng/anaconda3/envs/omg/lib/python3.6/site-packages/pyassimp/core.py", line 38, in AssimpLib
    load, load_mem, export, release, dll = helper.search_library()
  File "/home/yusheng/anaconda3/envs/omg/lib/python3.6/site-packages/pyassimp/helper.py", line 245, in search_library
    raise AssimpError("assimp library not found")
pyassimp.errors.AssimpError: assimp library not found

**Comment by kimkulling** [comment]
Works for pyaasimp4..1.4 but I have tested it for Windows. maybe that is the reason for the error.

**Comment by rpopovici** [comment]
I get the same error on windows 10 with python 3.7.7. I am building assimp from master with VS 2017. pyassimp 4.1.4 works only with assimp 1.4.0 release build

**Comment by tehzwen** [comment]
Yup, have the exact same error as @rpopovici using assimp 3.3 msi installer. Ended up downloading source for 5.0.1 and building using cmake + visual studio 2019 and the dll worked after that once placed inside of the `Lib/site-packages/pyassimp` folder

**Comment by Mr-Xia-6** [comment]
您的来信已收到，我会尽快处理~

**Comment by Mr-Xia-6** [comment]
您的来信已收到，我会尽快处理~
