### ISSUE TITLE
pyassimp: Converted OBJ (from DAE) can yield "setting an array element with a sequence" upon reload?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [assimp/assimp#3705]
**Describe the bug**
Another one related to #3703

When trying out the same code w/ a different DAE mesh (`shoulder.dae` instead of `base.dae`), I get a weird error about ragged NumPy arrays:
```sh
Original: shoulder.dae
  <everything's cool here>
Converted: shoulder.obj
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 183, in _init
    init = assimp_struct_inits[type(obj[0])]
KeyError: <class 'pyassimp.structs.LP_Mesh'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./repro.py", line 59, in <module>
    main()
  File "./repro.py", line 54, in main
    convert_mesh("shoulder.dae", "shoulder.obj", "obj")
  File "./repro.py", line 39, in convert_mesh
    scene_new = load_mesh(new_mesh_file)
  File "./repro.py", line 10, in load_mesh
    scene = pyassimp.load(mesh_file)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 319, in load
    scene = _init(model.contents)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 206, in _init
    raise e
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 187, in _init
    call_init(e, target)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 76, in call_init
    _init(obj.contents, obj, caller)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 218, in _init
    _finalize_mesh(self, target)
  File "/usr/lib/python3/dist-packages/pyassimp/core.py", line 410, in _finalize_mesh
    faces = numpy.array([f.indices for f in target.faces], dtype=numpy.int32)
ValueError: setting an array element with a sequence.
```

**To Reproduce**
- [code dir w/ readme](https://github.com/EricCousineau-TRI/repro/tree/b98dfda0a7395e336719bfac84984ef9d24f89cc/bug/assimp_mesh_dae_to_obj)
- [pyassimp code](https://github.com/EricCousineau-TRI/repro/blob/b98dfda0a7395e336719bfac84984ef9d24f89cc/bug/assimp_mesh_dae_to_obj/repro.py)
- [random shell code to repro](https://github.com/EricCousineau-TRI/repro/blob/b98dfda0a7395e336719bfac84984ef9d24f89cc/bug/assimp_mesh_dae_to_obj/setup_and_run.py)
- [text output](https://github.com/EricCousineau-TRI/repro/blob/b98dfda0a7395e336719bfac84984ef9d24f89cc/bug/assimp_mesh_dae_to_obj/output.txt)
- teh mesh: https://raw.githubusercontent.com/ros-industrial/universal_robot/c8c27c15/ur_description/meshes/ur10/visual/shoulder.dae

**Expected behavior**
pyassimp can load the same mesh that it can export?

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CPython 3.6.9
 - Browser: N/A
 - Version: Er, Ubuntu 18.04

**Smartphone (please complete the following information):**
N/A

**Additional context**
See #3703

**Comment by tellypresence** [comment]
Please add "Export" label to this issue

**Comment by tellypresence** [comment]
@EricCousineau-TRI Is this still a problem?

**Comment by tellypresence** [comment]
Closing due to no response
