### ISSUE TITLE
error 'GeneratorContextManager' object has no attribute 'meshes'

### ISSUE THREAD

**Issue by Mamartinezh** [assimp/assimp#3706]
**Describe the bug**
Hi! I'm new to assimp, I'm trying to load a model but when iterate over the meshes of the scene get this error : AttributeError: 'GeneratorContextManager' object has no attribute 'meshes'. I'm using python 2.7 and pyassimp, the assimp library compiled with CMake. Here is a snippe of the code that I'm trying to run using the load function of pyassimp, the object is a .OBJ format object and is just a plate (nothing fancy). Thank you in advance and regards!

**Screenshots**
![image](https://user-images.githubusercontent.com/64501300/111044844-f1752580-8418-11eb-9cef-e775357cd04d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by contriteobserver** [comment]
not able to reproduce this issue with this file, what is missing?
[plate.tar.gz](https://github.com/assimp/assimp/files/6154080/plate.tar.gz)
```
$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyassimp 
>>> source = "plate01.obj"
>>> scene = pyassimp.load(source, 0
... | pyassimp.postprocess.aiProcess_Triangulate
... | pyassimp.postprocess.aiProcess_SplitLargeMeshes
... | pyassimp.postprocess.aiProcess_GenNormals
... )
>>> for i, mesh in enumerate(scene.meshes):
...             print("num vertices(" + mesh.name + "): " + str(len(mesh.vertices)))
... 
num vertices(Plate): 9472
```

**Comment by MateoeslaLey** [comment]
@contriteobserver Which version of assimp are you ussing? I see you are using python 3.6.9, could that be?  Also, I'm not 100% sure of my assimp compilling, I'm getting some warnings for change in integer precission but I dont think that would affect... Honestly I've tried so many thing that at this point dont know what could be the probabbly cause. Thank you so much for you respond!! A little hope for solving this issue!

**Comment by contriteobserver** [comment]
just using python3-pyassimp 4.1.0

**Comment by manuel-koch** [comment]
I have the same issue ( even with current master = 939dacd ) when loading my OBJ file(s).
assimp = 5.0.1
pyassimp = master

Same issue when using the `plate01.obj` provided by @contriteobserver:

```
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.25.0
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35) 
[Clang 11.1.0 ] on darwin
In[2]: import pyassimp
In[3]: scene = pyassimp.load("plate01.obj")
In[4]: scene
Out[4]: <contextlib._GeneratorContextManager at 0x103ea62e0>
In[5]: for i, mesh in enumerate(scene.meshes):
  ...:     print("material index(" + mesh.name + "): " + str(mesh.materialindex))
  ...:    
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/item_opencascade/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-61b339bdedda>", line 1, in <module>
    for i, mesh in enumerate(scene.meshes):
AttributeError: '_GeneratorContextManager' object has no attribute 'meshes'
```

**Comment by Mark-Walen** [comment]
> **Describe the bug** Hi! I'm new to assimp, I'm trying to load a model but when iterate over the meshes of the scene get this error : AttributeError: 'GeneratorContextManager' object has no attribute 'meshes'. I'm using python 2.7 and pyassimp, the assimp library compiled with CMake. Here is a snippe of the code that I'm trying to run using the load function of pyassimp, the object is a .OBJ format object and is just a plate (nothing fancy). Thank you in advance and regards!
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/64501300/111044844-f1752580-8418-11eb-9cef-e775357cd04d.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10

The load function is wrapped by the contextmanager decorator. The following code snippet will work:

```python
import pyassimp

with pyassimp.load(source, flags) as scene:
    meshes = scene.mMeshes
```
I am using pyassimp v5.25. The scene class attributes define has changed, which  are similar to C++ scene struct definition now.

**Comment by tellypresence** [comment]
@Mamartinezh Did that workaround help?

**Comment by tellypresence** [comment]
Closing due to no response
