### ISSUE TITLE
Sometimes, the address-sanitizer CI check randomly fails at SplitLargeMeshesTest.testTriangleSplit. 

### ISSUE THREAD

**Issue by JC3** [assimp/assimp#3895]
Sometimes, the address-sanitizer CI check randomly fails at `SplitLargeMeshesTest.testTriangleSplit`. Looks like it runs out of memory or something.

I've run into this twice now in total. It always resolves itself if the checks are run again later.

I don't know anything about that system, so I can't really contribute anything else to this. Heck, I don't even know if "address-sanitizer CI check" makes sense as a phrase, 😅.

I found this in the test output window in the last PR I saw this in:

```
[ RUN      ] SplitLargeMeshesTest.testTriangleSplit
=================================================================
==2945==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62d0004ff0a0 at pc 0x00000052d0ea bp 0x7ffcc35332b0 sp 0x7ffcc3532a78
READ of size 12 at 0x62d0004ff0a0 thread T0
Info,  T0: Mesh exceeds the triangle limit. It will be split ...
    #0 0x52d0e9 in __asan_memcpy (/home/runner/work/assimp/assimp/build/bin/unit+0x52d0e9)
    #1 0x7f860e101e49 in Assimp::SplitLargeMeshesProcess_Triangle::SplitMesh(unsigned int, aiMesh*, std::vector<std::pair<aiMesh*, unsigned int>, std::allocator<std::pair<aiMesh*, unsigned int> > >&) /home/runner/work/assimp/assimp/build/../code/PostProcessing/SplitLargeMeshes.cpp:289:54
    #2 0x7fe5aa in SplitLargeMeshesTest_testTriangleSplit_Test::TestBody() /home/runner/work/assimp/assimp/build/../test/unit/utSplitLargeMeshes.cpp:140:24
    #3 0x8adb47 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2402:10
    #4 0x878e74 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2438:14
    #5 0x83f9d2 in testing::Test::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2474:5
    #6 0x841a73 in testing::TestInfo::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2656:11
    #7 0x842bfb in testing::TestCase::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2774:28
    #8 0x854116 in testing::internal::UnitTestImpl::RunAllTests() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:4649:43
    #9 0x8b5ef7 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2402:10
    #10 0x87e92f in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2438:14
    #11 0x85367a in testing::UnitTest::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:4257:10
    #12 0x560090 in RUN_ALL_TESTS() /home/runner/work/assimp/assimp/build/../contrib/gtest/include/gtest/gtest.h:2233:46
    #13 0x55ff72 in main /home/runner/work/assimp/assimp/build/../test/unit/Main.cpp:26:18
    #14 0x7f860d48a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #15 0x4b555d in _start (/home/runner/work/assimp/assimp/build/bin/unit+0x4b555d)

0x62d0004ff0a0 is located 0 bytes to the right of 36000-byte region [0x62d0004f6400,0x62d0004ff0a0)
allocated by thread T0 here:
    #0 0x55d51d in operator new[](unsigned long) (/home/runner/work/assimp/assimp/build/bin/unit+0x55d51d)
    #1 0x7fda67 in SplitLargeMeshesTest_testTriangleSplit_Test::TestBody() /home/runner/work/assimp/assimp/build/../test/unit/utSplitLargeMeshes.cpp:123:26
    #2 0x8adb47 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2402:10
    #3 0x878e74 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2438:14
    #4 0x83f9d2 in testing::Test::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2474:5
    #5 0x841a73 in testing::TestInfo::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2656:11
    #6 0x842bfb in testing::TestCase::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2774:28
    #7 0x854116 in testing::internal::UnitTestImpl::RunAllTests() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:4649:43
    #8 0x8b5ef7 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2402:10
    #9 0x87e92f in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:2438:14
    #10 0x85367a in testing::UnitTest::Run() /home/runner/work/assimp/assimp/build/../contrib/gtest/src/gtest.cc:4257:10
    #11 0x560090 in RUN_ALL_TESTS() /home/runner/work/assimp/assimp/build/../contrib/gtest/include/gtest/gtest.h:2233:46
    #12 0x55ff72 in main /home/runner/work/assimp/assimp/build/../test/unit/Main.cpp:26:18
    #13 0x7f860d48a0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/runner/work/assimp/assimp/build/bin/unit+0x52d0e9) in __asan_memcpy
Shadow bytes around the buggy address:
  0x0c5a80097dc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80097dd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80097de0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80097df0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c5a80097e00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c5a80097e10: 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80097e20: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80097e30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80097e40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80097e50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c5a80097e60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==2945==ABORTING
Error: Process completed with exit code 1.
```

**Comment by kimkulling** [comment]
Looks like a classic buffer overrun in the heap.

**Comment by aavenel** [comment]
I have been able to reproduce this bug in a reliable way.

`testTriangleSplit` is using random values without setting a seed.
This means that on every run we might have a different result.

I would advise to set a const seed for the unit-test.

If we use `srand(42)`, the test will fail every time.
If we use `srand(10)` test will succeed.

```cpp

TEST_F(SplitLargeMeshesTest, testTriangleSplit) {
    std::vector<std::pair<aiMesh *, unsigned int>> avOut;

    // generate many, many faces with randomized indices for
    // the second mesh

    // Pinning random seed
    //srand(10); //pass
    srand(42); //fail

    aiMesh *pcMesh2 = new aiMesh();
    pcMesh2->mNumVertices = 3000;
    pcMesh2->mVertices = new aiVector3D[pcMesh2->mNumVertices];
    pcMesh2->mNormals = new aiVector3D[pcMesh2->mNumVertices];

    pcMesh2->mNumFaces = 10000;
    pcMesh2->mFaces = new aiFace[pcMesh2->mNumFaces];

    for (unsigned int i = 0; i < pcMesh2->mNumFaces; ++i) {
        aiFace &face = pcMesh2->mFaces[i];
        face.mNumIndices = 3;
        face.mIndices = new unsigned int[3];
        face.mIndices[0] = (unsigned int)((rand() / (float)RAND_MAX) * pcMesh2->mNumVertices);
        face.mIndices[1] = (unsigned int)((rand() / (float)RAND_MAX) * pcMesh2->mNumVertices);
        face.mIndices[2] = (unsigned int)((rand() / (float)RAND_MAX) * pcMesh2->mNumVertices);
    }
```

**Comment by tellypresence** [comment]
@JC3 Is this still a problem?
