### ISSUE TITLE
Failing to import pyassimp

### ISSUE THREAD

**Issue by Fabijancic** [assimp/assimp#3897]
**Description of the bug**
Pyassimp fails to import after installing it with pip

**Steps to reproduce the behavior:**
1. Open a new venv
2. Install pyassimp
3. Create a new file try to import pyassimp and get an error
4. Error:
```
Traceback (most recent call last):
  File "/Users/fabijanc/projects/OpenGl-python/Svarog/pyassimp_test_2.py", line 1, in <module>
    import pyassimp
  File "/Users/fabijanc/projects/OpenGl-python/.venv/lib/python3.9/site-packages/pyassimp/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/fabijanc/projects/OpenGl-python/.venv/lib/python3.9/site-packages/pyassimp/core.py", line 33, in <module>
    class AssimpLib(object):
  File "/Users/fabijanc/projects/OpenGl-python/.venv/lib/python3.9/site-packages/pyassimp/core.py", line 37, in AssimpLib
    load, load_mem, export, export_blob, release, dll = helper.search_library()
  File "/Users/fabijanc/projects/OpenGl-python/.venv/lib/python3.9/site-packages/pyassimp/helper.py", line 255, in search_library
    raise AssimpError("assimp library not found")
pyassimp.errors.AssimpError: assimp library not found

Process finished with exit code 1
```

**Expected behavior**
Pyassimp imports without errors.

**Environment**
 - OS: macOS Catalina Version 10.15.7
 - Python 3.9.4
 - pip 21.0.1
 - pyassimp 4.1.4

**Comment by kimkulling** [comment]
Good point. I have obversed that behaviour as well.

**Comment by kimkulling** [comment]
Just double-checked the documentation which you can find here: https://pypi.org/project/pyassimp/

You need to install the latest version first before you can use the library, So at first, you just have to install the native libraries.
