### ISSUE TITLE
Bug : invalid test file(SEGV)::importTestCubeCompressed

### ISSUE THREAD

**Issue by autofuzzoss** [assimp/assimp#4298]
Describe the bug
A bug was found within the assimp. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using assimp. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "utXImporter.importTestCubeCompressed"
This may cause problems in the use of libraries
When you read this test file
SEGV error is triggered during the Running InternReadFile function
I think this code is needed to be exceptional processing for the unintended number.

==110125==ERROR: AddressSanitizer: SEGV on unknown address 0x612000f79880 (pc 0x7f66d1c7135e bp 0x7ffd4f378070 sp 0x7ffd4f3777f8 T0)
==110125==The signal is caused by a READ memory access.
    #0 0x7f66d1c7135d  /build/glibc-S9d2JN/glibc-2.27/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:285
    #1 0x592fad in __asan_memcpy (assimp/build/bin/unit+0x592fad)
    #2 0x1f83f52 in Assimp::XFileImporter::CreateMeshes(aiScene*, aiNode*, std::vector<Assimp::XFile::Mesh*, std::allocator<Assimp::XFile::Mesh*> > const&) assimp/code/AssetLib/X/XFileImporter.cpp:348:56
    #3 0x1f7d406 in Assimp::XFileImporter::CreateNodes(aiScene*, aiNode*, Assimp::XFile::Node const*) assimp/code/AssetLib/X/XFileImporter.cpp:220:5
    #4 0x1f7d68f in Assimp::XFileImporter::CreateNodes(aiScene*, aiNode*, Assimp::XFile::Node const*) assimp/code/AssetLib/X/XFileImporter.cpp:228:36
    #5 0x1f7a5e6 in Assimp::XFileImporter::CreateDataRepresentationFromImport(aiScene*, Assimp::XFile::Scene*) assimp/code/AssetLib/X/XFileImporter.cpp:150:25
    #6 0x1f7a095 in Assimp::XFileImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) assimp/code/AssetLib/X/XFileImporter.cpp:134:5
    #7 0xb280fa in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) assimp/code/Common/BaseImporter.cpp:112:9
    #8 0xb65bd0 in Assimp::Importer::ReadFile(char const*, unsigned int) assimp/code/Common/Importer.cpp:675:30

How To Reproduce
Download the attached file
Execute reproduce.sh
assimp/build/bin/unit --gtest_filter="utXImporter.importTestCubeCompressed"

Expected behavior
This can always cause problems when reading an invalid test file. Exception handling is required for reading an invalid test file.

Platform (please complete the following information):
OS: Ubuntu 18.04
[assimp_bug3.tar.gz](https://github.com/assimp/assimp/files/7777876/assimp_bug3.tar.gz)

**Comment by tellypresence** [comment]
Please add "Fuzzer" label to this issue

**Comment by tellypresence** [comment]
@autofuzzoss Is this still a problem?

**Comment by tellypresence** [comment]
Will track via epic #6128
