### ISSUE TITLE
Bug : invalid test file(SEGV)::crash_in_anim_mesh_destructor

### ISSUE THREAD

**Issue by autofuzzoss** [assimp/assimp#4299]
Describe the bug
A bug was found within the assimp. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using assimp. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "utglTF2ImportExport.crash_in_anim_mesh_destructor"
This may cause problems in the use of libraries
When you read this test file
SEGV error is triggered during the Running InternReadFile function
I think this code is needed to be exceptional processing for the unintended number.

==51563==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000021ba507 bp 0x7ffc6a641b60 sp 0x7ffc6a641b40 T0)
==51563==The signal is caused by a READ memory access.
==51563==Hint: address points to the zero page.
    #0 0x21ba506 in std::vector<glTF2::Node*, std::allocator<glTF2::Node*> >::operator[](unsigned long) /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/stl_vector.h:798:25
    #1 0x218589f in glTFCommon::Ref<glTF2::Node>::operator->() assimp/code/AssetLib/glTF/glTFCommon.h:305:30
    #2 0x253e6bd in ExportSkin(glTF2::Asset&, aiMesh const*, glTFCommon::Ref<glTF2::Mesh>&, glTFCommon::Ref<glTF2::Buffer>&, glTFCommon::Ref<glTF2::Skin>&, std::vector<aiMatrix4x4t<float>, std::allocator<aiMatrix4x4t<float> > >&) assimp/code/AssetLib/glTF2/glTF2Exporter.cpp:943:30
    #3 0x2532c5d in Assimp::glTF2Exporter::ExportMeshes() assimp/code/AssetLib/glTF2/glTF2Exporter.cpp:1143:13
    #4 0x252ab32 in Assimp::glTF2Exporter::glTF2Exporter(char const*, Assimp::IOSystem*, aiScene const*, Assimp::ExportProperties const*, bool) assimp/code/AssetLib/glTF2/glTF2Exporter.cpp:105:5
    #5 0x252a427 in Assimp::ExportSceneGLB2(char const*, Assimp::IOSystem*, aiScene const*, Assimp::ExportProperties const*) assimp/code/AssetLib/glTF2/glTF2Exporter.cpp:82:19
    #6 0xc011cc in Assimp::Exporter::Export(aiScene const*, char const*, char const*, unsigned int, Assimp::ExportProperties const*) assimp/code/Common/Exporter.cpp:495:17

How To Reproduce
Download the attached file
Execute reproduce.sh
assimp/build/bin/unit --gtest_filter="utglTF2ImportExport.crash_in_anim_mesh_destructor"

Expected behavior
This can always cause problems when reading an invalid test file. Exception handling is required for reading an invalid test file.

Platform (please complete the following information):
OS: Ubuntu 18.04
[assimp_bug4.tar.gz](https://github.com/assimp/assimp/files/7777877/assimp_bug4.tar.gz)

**Comment by tellypresence** [comment]
Please add "Fuzzer" label to this issue

**Comment by tellypresence** [comment]
@autofuzzoss Is this still a problem?

**Comment by tellypresence** [comment]
Closing due to no response to followup

**Comment by tellypresence** [comment]
Will track via epic #6128
