### ISSUE TITLE
Bug : invalid test file(SEGV)::importBinaryPLY

### ISSUE THREAD

**Issue by autofuzzoss** [assimp/assimp#4300]
Describe the bug
A bug was found within the assimp. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using assimp. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "utPLYImportExport.importBinaryPLY"
This may cause problems in the use of libraries
When you read this test file
SEGV error is triggered during the Running InternReadFile function
I think this code is needed to be exceptional processing for the unintended number.

==109064==ERROR: AddressSanitizer: SEGV on unknown address 0x6086eaeafb5c (pc 0x0000006070dc bp 0x7ffd60a3cb30 sp 0x7ffd60a3cac0 T0)
==109064==The signal is caused by a READ memory access.
    #0 0x6070db in aiVector3t<float>::operator==(aiVector3t<float> const&) const assimp/include/assimp/vector3.inl:201:14
    #1 0xc28c0a in Assimp::FindDegeneratesProcess::ExecuteOnMesh(aiMesh*) assimp/code/PostProcessing/FindDegenerates.cpp:194:58
    #2 0xc27918 in Assimp::FindDegeneratesProcess::Execute(aiScene*) assimp/code/PostProcessing/FindDegenerates.cpp:101:96
    #3 0x273ff2c in Assimp::BaseProcess::ExecuteOnScene(Assimp::Importer*) assimp/code/Common/BaseProcess.cpp:78:9
    #4 0xb693f6 in Assimp::Importer::ApplyPostProcessing(unsigned int) assimp/code/Common/Importer.cpp:807:22
    #5 0xb66a37 in Assimp::Importer::ReadFile(char const*, unsigned int) assimp/code/Common/Importer.cpp:717:13

How To Reproduce
Download the attached file
Execute reproduce.sh
assimp/build/bin/unit --gtest_filter="utPLYImportExport.importBinaryPLY"

Expected behavior
This can always cause problems when reading an invalid test file. Exception handling is required for reading an invalid test file.

Platform (please complete the following information):
OS: Ubuntu 18.04
[assimp_bug5.tar.gz](https://github.com/assimp/assimp/files/7777880/assimp_bug5.tar.gz)

**Comment by tellypresence** [comment]
Please add "Fuzzer" label to this issue

**Comment by TinyTinni** [comment]
Cannot reproduce with ac5988422a7f1898b25c13fb5fb068c646a4c544
