### ISSUE TITLE
Bug : invalid test file(SEGV)::TestFormatDetection

### ISSUE THREAD

**Issue by autofuzzoss** [assimp/assimp#4301]
Describe the bug
A bug was found within the assimp. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using assimp. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "utXImporter.TestFormatDetection"
This may cause problems in the use of libraries
When you read this test file
SEGV error is triggered during the Running InternReadFile function
I think this code is needed to be exceptional processing for the unintended number.

```
==112933==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x7f1831961366 bp 0x7fffce3a3310 sp 0x7fffce3a2a88 T0)
==112933==The signal is caused by a WRITE memory access.
==112933==Hint: address points to the zero page.
    #0 0x7f1831961365  /build/glibc-S9d2JN/glibc-2.27/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:308
    #1 0x4f2f52 in __interceptor_memcpy.part.40 (/ssd_array/utopia_paper/fuzz-test-generation/tmp/report_source/segv/Group21/assimp/build/bin/unit+0x4f2f52)
    #2 0x7f1831641eb3 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x124eb3)
    #3 0xe55553 in Assimp::ASE::Parser::ParseString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char const*) assimp/code/AssetLib/ASE/ASEParser.cpp:766:9
    #4 0xe5751b in Assimp::ASE::Parser::ParseLV2MaterialBlock(Assimp::ASE::Material&) assimp/code/AssetLib/ASE/ASEParser.cpp:519:22
    #5 0xe5385b in Assimp::ASE::Parser::ParseLV1MaterialListBlock() assimp/code/AssetLib/ASE/ASEParser.cpp:496:17
    #6 0xe5143a in Assimp::ASE::Parser::Parse() assimp/code/AssetLib/ASE/ASEParser.cpp:259:17
    #7 0xe0cd22 in Assimp::ASEImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) assimp/code/AssetLib/ASE/ASELoader.cpp:168:14
    #8 0xb280fa in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) assimp/code/Common/BaseImporter.cpp:112:9
    #9 0xb65bd0 in Assimp::Importer::ReadFile(char const*, unsigned int) assimp/code/Common/Importer.cpp:675:30

```
How To Reproduce
Download the attached file
Execute reproduce.sh
assimp/build/bin/unit --gtest_filter="utXImporter.TestFormatDetection"

Expected behavior
This can always cause problems when reading an invalid test file. Exception handling is required for reading an invalid test file.

Platform (please complete the following information):
OS: Ubuntu 18.04

[assimp_bug6.tar.gz](https://github.com/assimp/assimp/files/7777883/assimp_bug6.tar.gz)

**Comment by tellypresence** [comment]
@autofuzzoss Is this still a problem?

**Comment by tellypresence** [comment]
Closing due to no response to followup

**Comment by tellypresence** [comment]
Will track via epic #6128
