### ISSUE TITLE
Bug : invalid test file(SEGV)::duplicateSequenceGroupNames

### ISSUE THREAD

**Issue by autofuzzoss** [assimp/assimp#4308]
Describe the bug
A bug was found within the assimp. Though it might not be an intended use of the relevant API, the bug can still produce critical issues within a program using assimp. It would be best if the affected logic is checked beforehand.
The bug was found with a fuzzer based on the function "utMDLImporter_HL1_Nodes.duplicateSequenceGroupNames"
This may cause problems in the use of libraries
When you read this test file
SEGV error is triggered during the Running InternReadFile function
I think this code is needed to be exceptional processing for the unintended number.

```
==60907==ERROR: AddressSanitizer: SEGV on unknown address 0x6240002c6152 (pc 0x00000126d9d5 bp 0x7ffd6ec09310 sp 0x7ffd6ec08aa0 T0)
==60907==The signal is caused by a READ memory access.
    #0 0x126d9d4 in Assimp::MDL::HalfLife::HL1MDLLoader::read_animations() assimp/code/AssetLib/MDL/HalfLife/HL1MDLLoader.cpp:1001:29
    #1 0x1257357 in Assimp::MDL::HalfLife::HL1MDLLoader::load_file() assimp/code/AssetLib/MDL/HalfLife/HL1MDLLoader.cpp:170:13
    #2 0x1256bdd in Assimp::MDL::HalfLife::HL1MDLLoader::HL1MDLLoader(aiScene*, Assimp::IOSystem*, unsigned char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::MDL::HalfLife::HL1ImportSettings const&) assimp/code/AssetLib/MDL/HalfLife/HL1MDLLoader.cpp:101:5
    #3 0x121facb in Assimp::MDLImporter::InternReadFile_HL1(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) assimp/code/AssetLib/MDL/MDLLoader.cpp:1966:28
    #4 0x1210fdb in Assimp::MDLImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) assimp/code/AssetLib/MDL/MDLLoader.cpp:249:17
    #5 0xb280fa in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) assimp/code/Common/BaseImporter.cpp:112:9
    #6 0xb65bd0 in Assimp::Importer::ReadFile(char const*, unsigned int) assimp/code/Common/Importer.cpp:675:30

```

How To Reproduce
Download the attached file
Execute reproduce.sh
assimp/build/bin/unit --gtest_filter="utMDLImporter_HL1_Nodes.duplicateSequenceGroupNames"

Expected behavior
This can always cause problems when reading an invalid test file. Exception handling is required for reading an invalid test file.

Platform (please complete the following information):
OS: Ubuntu 18.04
[assimp_bug13.tar.gz](https://github.com/assimp/assimp/files/7782140/assimp_bug13.tar.gz)

**Comment by tellypresence** [comment]
@autofuzzoss Is this still a problem?

**Comment by tellypresence** [comment]
Closing due to no response to followup

**Comment by kimkulling** [comment]
Yes, still an issue.

**Comment by tellypresence** [comment]
Will track via epic #6128
