### ISSUE TITLE
Bug: pyassimp.load is causing jupyter notebook kernel to crash

### ISSUE THREAD

**Issue by calvinchang33** [assimp/assimp#4893]
**Describe the bug**
```
import pyassimp 
filename = r".\test\models\OBJ\box.obj"
scene = pyassimp.load(filename)
```

Error:
```
Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
```

Log file:
```
info 12:21:58.791: Dispose Kernel process 19972.
error 12:21:58.791: Raw kernel process exited code: 3221225477
error 12:21:58.792: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\Bolt\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:32353)
	at c:\Users\Bolt\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:51405
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\Bolt\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:51390)
	at y.dispose (c:\Users\Bolt\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:44872)
	at c:\Users\Bolt\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2184547
	at t.swallowExceptions (c:\Users\Bolt\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:7:125449)
	at p.dispose (c:\Users\Bolt\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2184525)
	at t.RawSession.dispose (c:\Users\Bolt\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2189519)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 12:21:58.792: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 12:21:58.793: Cancel all remaining cells true || Error || undefined
```

**To Reproduce**
1) pip install pyassimp
2) build assimp for .dll 
3) relocate .dll into Libs/site-packages/pyassimp
4) try to load .obj file using pyasimp.load

**Expected behavior**
pyassimp loads the specified file.

**Platform (please complete the following information):**
Windows, python 3.10.9

**Comment by kimkulling** [comment]
Doy ou have a callstack from the binary assimp lib?

**Comment by tellypresence** [comment]
Closing due to no response to triage followup
