### ISSUE TITLE
Bug: crash when loading any mdl7 with animation bones (3d game studio)

### ISSUE THREAD

**Issue by dicosky** [assimp/assimp#5059]
**Describe the bug**
the game crash when loading mdl7 model from gamestudio

**To Reproduce**
just load the model with aiImportFile.
const aiScene* scene = aiImportFile("model_mdl7.mdl",aiProcess_Triangulate );

**Expected behavior**
loading animation

**Platform (please complete the following information):**
windows

**Additional context**
assimp can load the model correctly from mdl5 and mdl7 without animations (skeleton).

**Comment by tellypresence** [comment]
Can you attached a sample `.mdl7` model that allows reproducing the error?

**Comment by dicosky** [comment]
> Can you attach a sample `.mdl7` model that allows reproducing the error?

sure, here is [examplemdl](https://www.mediafire.com/file/alvhazr2ajl8czj/examp.mdl/file)

**Comment by turol** [comment]
AddressSanitizer says:
```
==3307068==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6020000063f8 at pc 0x5625040e93c6 bp 0x7ffe208b0d50 sp 0x7ffe208b0d48
WRITE of size 8 at 0x6020000063f8 thread T0
    #0 0x5625040e93c5 in Assimp::MDLImporter::GenerateOutputMeshes_3DGS_MDL7(Assimp::MDL::IntGroupData_MDL7&, Assimp::MDL::IntSplitGroupData_MDL7&) assimp/code/AssetLib/MDL/MDLLoader.cpp:1914
    #1 0x5625040e2ba5 in Assimp::MDLImporter::InternReadFile_3DGS_MDL7() assimp/code/AssetLib/MDL/MDLLoader.cpp:1526
    #2 0x5625040d3490 in Assimp::MDLImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) assimp/code/AssetLib/MDL/MDLLoader.cpp:231
    #3 0x562503d26f40 in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) assimp/code/Common/BaseImporter.cpp:110
    #4 0x56250392f73b in Assimp::Importer::ReadFile(char const*, unsigned int) assimp/code/Common/Importer.cpp:723
    #5 0x56250391a5fb in Assimp::Importer::ReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) assimp/include/assimp/Importer.hpp:670
    #6 0x562503917bcc in ImportModel(ImportData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) assimp/tools/assimp_cmd/Main.cpp:307
    #7 0x562503922886 in Assimp_Info(char const* const*, unsigned int) assimp/tools/assimp_cmd/Info.cpp:344
    #8 0x562503917670 in main assimp/tools/assimp_cmd/Main.cpp:222
    #9 0x7f6104046189 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #10 0x7f6104046244 in __libc_start_main_impl ../csu/libc-start.c:381
    #11 0x5625038f1540 in _start (/home/turo/softaa/assimp/asan/bin/assimp+0x2b2540) (BuildId: 3adb6fc4d3c9fe0fe52a226eb131d8e5a467fb6e)

0x6020000063f8 is located 64 bytes after 8-byte region [0x6020000063b0,0x6020000063b8)
allocated by thread T0 here:
    #0 0x7f61046d9268 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:98
    #1 0x5625040e9242 in Assimp::MDLImporter::GenerateOutputMeshes_3DGS_MDL7(Assimp::MDL::IntGroupData_MDL7&, Assimp::MDL::IntSplitGroupData_MDL7&) assimp/code/AssetLib/MDL/MDLLoader.cpp:1907
    #2 0x5625040e2ba5 in Assimp::MDLImporter::InternReadFile_3DGS_MDL7() assimp/code/AssetLib/MDL/MDLLoader.cpp:1526
    #3 0x5625040d3490 in Assimp::MDLImporter::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, aiScene*, Assimp::IOSystem*) assimp/code/AssetLib/MDL/MDLLoader.cpp:231
    #4 0x562503d26f40 in Assimp::BaseImporter::ReadFile(Assimp::Importer*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Assimp::IOSystem*) assimp/code/Common/BaseImporter.cpp:110
    #5 0x56250392f73b in Assimp::Importer::ReadFile(char const*, unsigned int) assimp/code/Common/Importer.cpp:723
    #6 0x56250391a5fb in Assimp::Importer::ReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) assimp/include/assimp/Importer.hpp:670
    #7 0x562503917bcc in ImportModel(ImportData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) assimp/tools/assimp_cmd/Main.cpp:307
    #8 0x562503922886 in Assimp_Info(char const* const*, unsigned int) assimp/tools/assimp_cmd/Info.cpp:344
    #9 0x562503917670 in main assimp/tools/assimp_cmd/Main.cpp:222
    #10 0x7f6104046189 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```

Something wrong with the bones.

**Comment by turol** [comment]
`pcMesh->mNumBones` is 1. `aaiVWeightList` has 30 elements. The loop early-outs for the first 8 because `(*k).empty()`. Number 9 writes outside the allocated area and crashes.

**Comment by tellypresence** [comment]
Directly attaching 3D model linked above in case it goes away: [`examp_mdl.zip`](https://github.com/user-attachments/files/19578330/examp_mdl.zip)

**Comment by tellypresence** [comment]
Please add label "MDL" to this issue

**Comment by tellypresence** [comment]
Sounds like the 3D model itself has problems, closing
