### ISSUE TITLE
Bug: Segmentation fault while importing Blender v2.76 model

### ISSUE THREAD

**Issue by stephengold** [assimp/assimp#5346]
**Describe the bug**
`assimp info mummy.blend` terminates prematurely with a segmentation fault

**To Reproduce**
1. Build the `assimp` tool (I used master branch at Git hash=56e0ba5)
2. Download the archive file: 
[test.zip](https://github.com/assimp/assimp/files/13465438/test.zip)
3. Extract the "mummy.blend" model from the archive.
4. Run the `assimp` tool on the model. 

**Expected behavior**
Either print information about the model or diagnose what's wrong with it.

**Screenshots**
Here's how the model looks in Blender:

**Platform (please complete the following information):**
 - OS: Linux Mint
 - Browser: Firefox

**Additional context**
Here's the stack trace of the crash from GDB:
```console
$ gdb bin/assimpd
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin/assimpd...
(gdb) run info mummy.blend
Starting program: /home/sgold/NetBeansProjects/ext/assimp/build/bin/assimpd info mummy.blend
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Launching asset import ...           OK
Validating postprocessing flags ...  OK

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff756c9c0 in std::__shared_ptr<Assimp::Blender::MTex, (__gnu_cxx::_Lock_policy)2>::operator bool (this=0x598) at /usr/include/c++/11/bits/shared_ptr_base.h:1300
1300	      { return _M_ptr != nullptr; }
(gdb) bt
#0  0x00007ffff756c9c0 in std::__shared_ptr<Assimp::Blender::MTex, (__gnu_cxx::_Lock_policy)2>::operator bool (this=0x598) at /usr/include/c++/11/bits/shared_ptr_base.h:1300
#1  0x00007ffff756593a in Assimp::BlenderImporter::ConvertMesh (this=0x55555559def0, 
    mesh=0x5555555af740, conv_data=..., temp=...)
    at /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/Blender/BlenderLoader.cpp:947
#2  0x00007ffff7567ba1 in Assimp::BlenderImporter::ConvertNode (this=0x55555559def0, in=..., 
    obj=0x5555555af1d0, conv_data=..., parentTransform=...)
    at /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/Blender/BlenderLoader.cpp:1213
#3  0x00007ffff7561ff9 in Assimp::BlenderImporter::ConvertBlendFile (this=0x55555559def0, 
    out=0x5555555a0e30, in=..., file=...)
    at /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/Blender/BlenderLoader.cpp:306
#4  0x00007ffff7560f40 in Assimp::BlenderImporter::InternReadFile (this=0x55555559def0, 
    pFile="mummy.blend", pScene=0x5555555a0e30, pIOHandler=0x7fffffffcb90)
    at /home/sgold/NetBeansProjects/ext/assimp/code/AssetLib/Blender/BlenderLoader.cpp:160
#5  0x00007ffff724a2cf in Assimp::BaseImporter::ReadFile (this=0x55555559def0, 
    pImp=0x7fffffffd810, pFile="mummy.blend", pIOHandler=0x55555559b640)
    at /home/sgold/NetBeansProjects/ext/assimp/code/Common/BaseImporter.cpp:135
#6  0x00007ffff7263d42 in Assimp::Importer::ReadFile (this=0x7fffffffd810, 
    _pFile=0x7fffffffd310 "mummy.blend", pFlags=3645131)
    at /home/sgold/NetBeansProjects/ext/assimp/code/Common/Importer.cpp:709
#7  0x000055555557560c in Assimp::Importer::ReadFile (this=0x7fffffffd810, pFile="mummy.blend", 
    pFlags=3645131) at /home/sgold/NetBeansProjects/ext/assimp/include/assimp/Importer.hpp:670
#8  0x000055555557404c in ImportModel (imp=..., path="mummy.blend")
    at /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Main.cpp:307
#9  0x0000555555578ea7 in Assimp_Info (params=0x7fffffffddb8, num=1)
    at /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Info.cpp:344
#10 0x0000555555573d2f in main (argc=3, argv=0x7fffffffdda8)
    at /home/sgold/NetBeansProjects/ext/assimp/tools/assimp_cmd/Main.cpp:222
(gdb) 
```

I set a breakpoint on "BlenderLoader.cpp" line 947. It looks like `pMat` is `NULL`.

**Comment by stephengold** [comment]
Here is the output with verbose logging enabled (Assimp Git hash=56e0ba5):
```console
Info,  T0: Load mummy/mummy.blend
Debug, T0: Assimp 5.3.0 amd64 gcc shared singlethreadedsingle : 
Info,  T0: Found a matching importer for this file format: Blender 3D Importer (http://www.blender3d.org).
Info,  T0: Import root directory is 'mummy/'
Info,  T0: BLEND: Blender version is 2.76 (64bit: true, little endian: true)
Debug, T0: BlenderDNA: Got 604 structures with totally 6955 fields
Warn,  T0: BlendDNA: Did not find a field named `*master_collection` in structure `Scene`
Info,  T0: (Stats) Fields read: 211938, pointers resolved: 10, cache hits: 2, cached objects: 4
```

**Comment by kimkulling** [comment]
I will close this one.

**Comment by turol** [comment]
If you intend to deprecate the Blender loader you should
1. Decide on a deprecation/removal schedule
2. Add a runtime warning when the loader is used to lets users know
3. Disable building it after some releases
4. Remove the code after some more releases

**Comment by kimkulling** [comment]
Yes, I will do this.
