### ISSUE TITLE
Bug: "hunter" CI merge checks failing for PRs

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5373]
Submitted a simple PR (comments out 3 lines in 1 file) and the 3 "hunter" merge checks fail:
<img alt="hunter_errors_Screenshot 2023-12-09 194707" src="https://github.com/assimp/assimp/assets/26958898/e6a934d3-e744-421e-a9c4-fa861869fbef" width=480 />

- `C/C++ CI / ubuntu-gcc-hunter-build-and-test (pull_request) Failing`
- `C/C++ CI / macos-clang-hunter-build-and-test (pull_request) Failing`
- `C/C++ CI / windows-msvc-hunter-build-and-test (pull_request) Failing`

Error is identical for all 3 checks:
```
Error: "CMake failed with error code: '1'.
    at CMakeRunner.<anonymous> (/Users/runner/work/_actions/lukka/run-cmake/v3/dist/index.js:4065:31)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/_actions/lukka/run-cmake/v3/dist/index.js:3870:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: run-cmake action execution failed: 'Error: "CMake failed with error code: '1'.'
```

**Comment by turol** [comment]
That's not useful. It's the runner telling us that CMake failed. What is the CMake error message?

**Comment by kimkulling** [comment]
Is hinter still maintained? ll things I found were really old. So currently all Hunter stuff is disabled until I  have found a working solution.
