### ISSUE TITLE
Bug: PR/CI cmake, unit test failures, segfault

### ISSUE THREAD

**Issue by tellypresence** [assimp/assimp#5523]
#### g++/win cl.exe seem to fail on cmake:

`ubuntu-latest-g++-built-and-test`
```
Build with CMake
⏱ elapsed: 218.823 seconds
Error: "Build failed with error code: '1'."
    at Function.<anonymous> (/home/runner/work/_actions/lukka/run-cmake/v3/dist/index.js:4117:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/lukka/run-cmake/v3/dist/index.js:3870:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: run-cmake action execution failed: 'Error: "Build failed with error code: '1'."'
```

`windows-latest-cl.exe-built-and-test`
```
Build with CMake
⏱ elapsed: 152.732 seconds
Error: "Build failed with error code: '1'."
    at Function.<anonymous> (D:\a\_actions\lukka\run-cmake\v3\dist\index.js:4117:23)
    at Generator.next (<anonymous>)
    at fulfilled (D:\a\_actions\lukka\run-cmake\v3\dist\index.js:3870:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: run-cmake action execution failed: 'Error: "Build failed with error code: '1'."'
```

#### For clang++ looks like there may be a segfault in the runner after some failures

`macos-latest-clang++-built-and-test`: segfault
```
Error, T0: Validation failed: A node of the scene-graph is nullptr
/Users/runner/work/assimp/assimp/test/unit/utXImporterExporter.cpp:119: Failure
Expected: (nullptr) != (scene), actual: (nullptr) vs NULL
 [  FAILED  ] utXImporter.TestFormatDetection (0 ms)
...
 Error, T0: Validation failed: A node of the scene-graph is nullptr
/Users/runner/work/assimp/assimp/test/unit/utDXFImporterExporter.cpp:66: Failure
Expected: (nullptr) != (scene), actual: (nullptr) vs NULL
[  FAILED  ] utDXFImporterExporter.importerWithoutExtensionTest (6 ms)
...
 /Users/runner/work/assimp/assimp/test/unit/utObjImportExport.cpp:237: Failure
Value of: differ.isEqual(expected, scene)
  Actual: false
Expected: true
Number of meshes not equal ( expected: 1, found : 0 )
[  FAILED  ] utObjImportExport.obj_import_test (0 ms)
...
 Error, T0: Validation failed: A node of the scene-graph is nullptr
/Users/runner/work/assimp/assimp/test/unit/utObjImportExport.cpp:283: Failure
Value of: differ.isEqual(scene, sceneReImport)
  Actual: false
Expected: true
[  FAILED  ] utObjImportExport.issue1923_vertex_color_Test (4 ms)
...
 Error, T0: Validation failed: A node of the scene-graph is nullptr
/Users/runner/work/assimp/assimp/test/unit/utObjImportExport.cpp:363: Failure
Expected: (nullptr) != (scene), actual: (nullptr) vs NULL
/Users/runner/work/_temp/8348ed48-95cb-44ad-a852-1881124f2e84.sh: line 1:  7028 Segmentation fault: 11  ./unit
Error: Process completed with exit code 139.
```

`ubuntu-latest-clang++-built-and-test`: segfault w/coredump:
```
Error, T0: Validation failed: A node of the scene-graph is nullptr
/home/runner/work/assimp/assimp/test/unit/utObjImportExport.cpp:363: Failure
Expected: (nullptr) != (scene), actual: (nullptr) vs NULL

/home/runner/work/_temp/bb07bc7c-87f3-4381-83de-f067028baf3c.sh: line 1:  3013 Segmentation fault      (core dumped) ./unit
Error: Process completed with exit code 139.
```

**Comment by kimkulling** [comment]
I wasn't able to reproduce this one. Do you have a branch where I can check this failure?
