### ISSUE TITLE
Failure to load some .blend files

### ISSUE THREAD

**Issue by mcmonkey4eva** [assimp/assimp#565]
I get this error in AssimpNet:

```
Assimp.AssimpException: Error importing file: Expected target to be of type `MTFace` but seemingly it is a `PreviewImage` instead
   at Assimp.AssimpContext.ImportFileFromStream(Stream stream, PostProcessSteps postProcessFlags, String formatHint)
```

When attempting to load a .blend file - I have a few plain lines (non-faces, just two vertices linked together) I haven't been able to track down yet, which might be related.

EDIT: Removed every line I could find, now getting

```
Assimp.AssimpException: Error importing file: Expected target to be of type `MTFace` but seemingly it is a `bPoseChannel` instead
   at Assimp.AssimpContext.ImportFileFromStream(Stream stream, PostProcessSteps postProcessFlags, String formatHint)
```

oh and I'm using a build I compiled off the master branch a few weeks ago

**Comment by kimkulling** [comment]
Deprecated.
