### ISSUE TITLE
Memory leak in aiGetPredefinedLogStream

### ISSUE THREAD

**Issue by YancyLii** [assimp/assimp#5700]
**Describe the bug**
The aiGetPredefinedLogStream function in the Assimp library causes an out-of-memory error when repeatedly called. This is due to a memory leak where allocated LogStream objects are not being released, leading to excessive memory usage and eventually crashing the program when the memory limit is exceeded.

**To Reproduce**
1.Run the provided testing program with the target code.
```
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    if (size < sizeof(float) * 4) {
        return 0;
    }

    // Extract data from input
    float vec1_x, vec1_y, vec2_x, vec2_y;
    memcpy(&vec1_x, data, sizeof(float));
    memcpy(&vec1_y, data + sizeof(float), sizeof(float));
    memcpy(&vec2_x, data + 2 * sizeof(float), sizeof(float));
    memcpy(&vec2_y, data + 3 * sizeof(float), sizeof(float));

    // Perform vector subtraction
    aiVector2D vec1(vec1_x, vec1_y);
    aiVector2D vec2(vec2_x, vec2_y);

    aiGetPredefinedLogStream(aiDefaultLogStream_STDOUT, nullptr);
    aiVector2Subtract(&vec1, &vec2);

    return 0;
}
```
2.Observe the memory usage steadily increase until it exceeds the limit, causing an out-of-memory error.

**Expected behavior**
The memory is not released, leading to a continuous increase in memory usage, which eventually causes an out-of-memory error.
```
==27795== ERROR: libFuzzer: out-of-memory (used: 2064Mb; limit: 2048Mb)
   To change the out-of-memory limit use -rss_limit_mb=<N>

Live Heap Allocations: 789470656 bytes in 38390624 chunks; quarantined: 202493194 bytes in 250632 chunks; 157322 other chunks; total chunks: 38798578; showing top 95% (at most 8 unique contexts)
460655640 byte(s) (58%) in 19193985 allocation(s)
    #0 0x56663d in operator new(unsigned long) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x56663d)
    #1 0x582e2b in __gnu_cxx::new_allocator<std::_List_node<Assimp::LogStream*> >::allocate(unsigned long, void const*) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/new_allocator.h:114:27
    #2 0x582db8 in std::allocator_traits<std::allocator<std::_List_node<Assimp::LogStream*> > >::allocate(std::allocator<std::_List_node<Assimp::LogStream*> >&, unsigned long) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/alloc_traits.h:443:20
    #3 0x582c11 in std::__cxx11::_List_base<Assimp::LogStream*, std::allocator<Assimp::LogStream*> >::_M_get_node() /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_list.h:438:16
    #4 0x582ad1 in std::_List_node<Assimp::LogStream*>* std::__cxx11::list<Assimp::LogStream*, std::allocator<Assimp::LogStream*> >::_M_create_node<Assimp::LogStream* const&>(Assimp::LogStream* const&) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_list.h:630:21
    #5 0x582a65 in void std::__cxx11::list<Assimp::LogStream*, std::allocator<Assimp::LogStream*> >::_M_insert<Assimp::LogStream* const&>(std::_List_iterator<Assimp::LogStream*>, Assimp::LogStream* const&) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_list.h:1907:18
    #6 0x574a09 in std::__cxx11::list<Assimp::LogStream*, std::allocator<Assimp::LogStream*> >::push_back(Assimp::LogStream* const&) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/stl_list.h:1208:15
    #7 0x56fcbe in aiGetPredefinedLogStream /volume/PromptDriver/exp/assimp/code/Common/Assimp.cpp:359:24
    #8 0x56a053 in LLVMFuzzerTestOneInput /volume/PromptDriver/results/assimp/driver/Test_assimp_Id1574.cc:77:5
    #9 0x471391 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x471391)
    #10 0x470ad5 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x470ad5)
    #11 0x472d77 in fuzzer::Fuzzer::MutateAndTestOne() (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x472d77)
    #12 0x473a75 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x473a75)
    #13 0x46242e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x46242e)
    #14 0x48b272 in main (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x48b272)
    #15 0x7f009fb8f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)

307103760 byte(s) (38%) in 19193985 allocation(s)
    #0 0x56663d in operator new(unsigned long) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x56663d)
    #1 0x58e148 in Assimp::Intern::AllocateFromAssimpHeap::operator new(unsigned long) /volume/PromptDriver/exp/assimp/code/Common/Importer.cpp:115:12
    #2 0x5a75dd in Assimp::LogStream::createDefaultStream(aiDefaultLogStream, char const*, Assimp::IOSystem*) /volume/PromptDriver/exp/assimp/code/Common/DefaultLogger.cpp:112:16
    #3 0x56fc00 in aiGetPredefinedLogStream /volume/PromptDriver/exp/assimp/code/Common/Assimp.cpp:351:25
    #4 0x56a053 in LLVMFuzzerTestOneInput /volume/PromptDriver/results/assimp/driver/Test_assimp_Id1574.cc:77:5
    #5 0x471391 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x471391)
    #6 0x470ad5 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x470ad5)
    #7 0x472d77 in fuzzer::Fuzzer::MutateAndTestOne() (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x472d77)
    #8 0x473a75 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x473a75)
    #9 0x46242e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x46242e)
    #10 0x48b272 in main (/volume/Fuzzer/fuzzer/assimp/Test_assimp_Id1574+0x48b272)
    #11 0x7f009fb8f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082)

MS: 5 InsertRepeatedBytes-InsertByte-ChangeBit-InsertRepeatedBytes-CopyPart-; base unit: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc


artifact_prefix='./'; Test unit written to ./oom-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
SUMMARY: libFuzzer: out-of-memory
```
**Platform (please complete the following information):**
 - OS: Ubuntu20.04

**Additional context**
Root Cause Analysis:
The primary issue is a memory leak in the aiGetPredefinedLogStream function. The function creates a new LogStream object and appends it to the global gPredefinedStreams list each time it is called, but these objects are never released, leading to continuous growth in memory usage.
Relevant Code:
ASSIMP_API aiLogStream aiGetPredefinedLogStream(aiDefaultLogStream pStream, const char *file) {
    aiLogStream sout;

    ASSIMP_BEGIN_EXCEPTION_REGION();
    LogStream *stream = LogStream::createDefaultStream(pStream, file);
    if (!stream) {
        sout.callback = nullptr;
        sout.user = nullptr;
    } else {
        sout.callback = &CallbackToLogRedirector;
        sout.user = (char *)stream;
    }
    gPredefinedStreams.push_back(stream);
    ASSIMP_END_EXCEPTION_REGION(aiLogStream);
    return sout;
}
Suggested Fix:
Implement a mechanism to properly release the memory allocated for LogStream objects when they are no longer needed.
Add limits and checks to the number and size of LogStream objects being created and stored in gPredefinedStreams.
Improve the fuzzer test to include memory cleanup code after each test run.

**Comment by kimkulling** [comment]
Thanks a lot for your detailed analysis. I do agree that releasing attached streams is nessesary.
